<?php
namespace Socketlabs;
/**
 * The response of an SocketLabsClient send request.
 */
class SendResponse{

    /**
     * The result of the SocketLabsClient send request. 
     */
    public $result;

    /**
     * A unique key generated by the Injection API if an unexpected error occurs during the SocketLabsClient send request.
     * This unique key can be used by SocketLabs support to troubleshoot the issue.
     */
    public $transactionReceipt;

    /**
     * An array of AddressResult objects that contain the status of each address that failed. If no messages failed this array is empty.
     */
    public $addressResults = array();

    /**
     * A message detailing why the SocketLabsClient send request failed.
     */
    public $responseMessage;

    /**
     * Create a new instance of SendResponse
     * @param SendResult $result
     */
    public function __construct($result = null){
        $this->result = $result;
    }
 
}